spring.application.name=online_library

# === PostgreSQL connection ===
spring.datasource.url=jdbc:postgresql://localhost:5432/online_library
spring.datasource.username=postgres
spring.datasource.password=$2a$14$3XUMvpYCNLVaxg4HDB0BtuN01V1HjDJ0UzdZw.mqW0g15X9ipnOC6

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === Port server ===
server.port=8080